### ISSUE TITLE
Make AI smarter using Machine Learning (?)

### ISSUE THREAD

**Issue by stefanhendriks** [Fundynamic/dune2themaker4j#58]
See:

https://github.com/haifengl/smile

We could possibly train the AI and let it decide what to do next based on previous attempts/learnings/input ?

What do you think @arjenvanderende ?

**Comment by arjenvanderende** [comment]
Sounds really cool and really complex :smile: Let's experiment with it to see if we can get some grip on how difficult it will be to learn the AI to play the game. Based on our experiences with that we can decide if we're going to use machine learning or stick with a more traditional AI implementation.

I'm was looking at [gdx-ai](https://github.com/libgdx/gdx-ai) earlier today, which might be nice to incorporate. Besides some state-based AI stuff it also contains path-finding and smoothing algorithms. That way we don't have to reinvent the wheel. We'll need to see if we can use the bare essentials though, because it seems to depend on [libgdx](https://github.com/libgdx/libgdx). Since we already use Slick we should not need that (unless you want to switch) :wink:

**Comment by stefanhendriks** [comment]
Looking at this issue, wondering which AI we have now (none). So I'll close it. It'll come up when we need to again.
